name: learn-github-actions
run-name: Updating blogs on server
on: [push]
jobs:
  update-server:
    runs-on: ubuntu-latest
    steps:
      - uses: D3rHase/ssh-command-action@v0.2.2
        with:
          # hostname / IP of the server
          host: 113.31.174.4
          # ssh port of the server
          port: 22
          # user of the server
          user: root
          # private ssh key registered on the server
          private_key: ${{secrets.SERVER_SSH_KEY}}
          # Fingerprint of the server, preventing man-in-the-middle attacks
          # host_fingerprint: # optional
          # command to be executed
          command: sh /root/AppData/Scripts/updateBlog.sh
        
